export const pfText =
  "Proyecto final grupal del bootcamp full stack en Soy Henry, desarrollado de forma colaborativa durante el periodo de un mes. El foco fue crear una solución para una empresa de logística en Argentina, donde participé especialmente en la implementación de funcionalidades para cotización de envíos, contratación y descarga de facturas, brindando una experiencia interactiva para los usuarios. Actualmente, estoy rehaciendo el proyecto desde cero con C# .NET, Next.js y React";

export const piText =
  "Proyecto individual del primer módulo del bootcamp de Soy Henry. El objetivo del ejercicio fue aplicar por primera vez herramientas del stack PERN en un desarrollo full stack desde cero. La app consume una API pública de países y permite listarlos, buscar por nombre, filtrar por continente y actividades, y ordenarlos alfabéticamente o por población. Incluye la creación de actividades turísticas mediante un formulario controlado con validaciones, rutas protegidas y lógica en el backend. El frontend fue desarrollado con React y Redux, mientras que el backend utiliza Node.js, Express, Sequelize y PostgreSQL.";
export const jspJavaText =
  "Este proyecto formó parte del primer módulo del curso de Java en la Universidad Nacional de Jujuy. Consiste en una aplicación web desarrollada con Maven para administrar profesores en una universidad, con funcionalidades para listar, registrar y eliminar profesores. La interfaz se implementó usando Servlets y JavaServer Pages (JSP), mientras que la persistencia se manejó mediante JPA con una base de datos MySQL creada con Workbench. El desarrollo se realizó en Java 17 usando NetBeans como entorno de trabajo.";
export const dotnetText =
  "El objetivo principal de este proyecto fue aprender y practicar la implementación de un sistema de autenticación usando ASP.NET Core MVC con cookies para manejo de sesiones. También integré autenticación externa con Google para entender OAuth y login moderno. Utilicé SQL Server para la persistencia de datos y desplegué la aplicación en Azure para familiarizarme con el proceso de publicación y administración en la nube.";

export const geoText = `El objetivo de este ejercicio fue practicar el uso de React con TypeScript implementando custom hooks, reutilización de componentes y la integración de mapas interactivos con Leaflet. Utilicé datos de la API pública de datos.gob.ar como fuente para probar la carga dinámica de información geográfica. La aplicación permite seleccionar una provincia, su departamento y localidad, y visualizar sus ubicaciones sobre un mapa.`;
